config/routes.rb
Rails.application.routes.draw do
  root "rooms#index"

  resources :users, only: [:new, :create] do
    get :activate, on: :member
    get :edit_password, on: :member
    post :update_password, on: :member
    put :update_password, on: :member
  end

  resource :users, only: [] do
    get :new_session
    post :create_session
    get :destroy_session
    get :new_act_email
    post :send_act_email
    get :new_reset_password
    post :create_reset_password
  end

  get "register" => "users#new",             as: :register
  get "login"    => "users#new_session",     as: :login
  get "logout"   => "users#destroy_session", as: :logout

  resources :rooms, only: [:index, :show]
  resource :rooms, only: [] do
    post :publish
  end

  resources :bids, only: [:create] do
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  email                           :string           not null
#  crypted_password                :string
#  salt                            :string
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  activation_state                :string
#  activation_code                 :string
#  activation_code_expires_at      :datetime
#  remember_me_token               :string
#  remember_me_token_expires_at    :datetime
#  reset_password_token            :string
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  last_login_at                   :datetime
#  last_logout_at                  :datetime
#  last_activity_at                :datetime
#  last_login_from_ip_address      :string
#  failed_logins_count             :integer          default(0)
#  lock_expires_at                 :datetime
#  amount_of_bids                  :integer          default(0)
#

class User < ApplicationRecord

  # constants
  #--------------------------------------------------------------
  PASSWORD_LENGTH = 8.freeze
  EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.freeze

  # authentication
  #--------------------------------------------------------------
  authenticates_with_sorcery!

  # associations
  #--------------------------------------------------------------
  has_many :bids, dependent: :destroy

  # validations
  #--------------------------------------------------------------
  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_format_of :email, with: EMAIL_REGEX, multiline: true
  validates_presence_of :password, :if => :password_required?
  validates_length_of :password, minimum: PASSWORD_LENGTH, :if => :password
  validates_confirmation_of :password, message: "should match the password", :if => :password

  # instance methods
  #--------------------------------------------------------------

  # is user active?
  def active?
    self.activation_state == "active"
  end

  # is user logged in?
  def logged_in?
    return false if self.last_login_at.nil?
    return true if self.last_logout_at.nil?
    self.last_login_at > self.last_logout_at
  end

  # resend the activation email
  def resend_activation_email!
    self.send_activation_needed_email!
  end

  private
  # if it's a new user the password is required
  def password_required?
    new_record?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new, :create, :activate, :new_act_email, :send_act_email, :new_session, :create_session, :destroy_session, :new_reset_password, :create_reset_password, :edit_password, :update_password]

  # User Registration
  #--------------------------------------------------------------
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to login_path, notice: "Registration successfull. Check your email for activation instructions."
    else
      render :action => "new"
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      redirect_to login_path, notice: "User was successfully activated."
    else
      not_authenticated
    end
  end

  # User Sessions (login/logout)
  #--------------------------------------------------------------
  def new_session
  end

  def create_session
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_to root_path, notice: "Login successfull."
    else
      flash.now[:alert] = "Login Failed!"; render action: "new_session"
    end
  end

  def destroy_session
    logout
    redirect_to root_path, notice: "Logged out!"
  end

  # Reset password
  #--------------------------------------------------------------
  def new_reset_password
  end

  def create_reset_password
    if user = User.find_by_email(params[:email])
      user.deliver_reset_password_instructions!
      redirect_to root_path, notice: "Instructions have been sent to your email."
    else
      flash.now[:alert] = "User does not exist."; render action: "new_reset_password"
    end
  end

  def edit_password
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated if !@user
  end

  def update_password
    @token = params[:token]
    @user = User.load_from_reset_password_token @token
    not_authenticated if !@user
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password! params[:user][:password]
      redirect_to login_path, notice: "Password was successfully updated."
    else
      render action: "edit_password"
    end
  end

  # Resend User Activation email
  #--------------------------------------------------------------
  def new_act_email
  end

  def send_act_email
    if user = User.find_by_email(params[:email])
      if user.active?
        redirect_to login_path, notice: "User is already Active. No need to resend activation email."
      else
        user.resend_activation_email!
        redirect_to root_path, notice: "Activation email resend. Check your email for instructions."
      end
    else
      flash.now[:alert] = "User does not exist."; render action: "new_act_email"
    end
  end


private

  # Generate strong parameters for user
  def user_params
    params.require(:user).permit :email, :password, :password_confirmation
  end

end

app/views/users/_form.html.erb
<%= form_for (@user), class: "form-signin" do |f| %>
  <%= f.text_field :email, class: "form-control", placeholder: "Email", autofocus: ""  %>
  <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
		<%= f.hidden_field :price_plan_id, value: 1 %>
  <%= f.submit class: "btn btn-lg btn-dark btn-block", id: "submit_user" %>
<% end %>

app/views/users/edit_password.html.erb
<% title "Reset your Password" %>

<div class="row">
  <div class="col-md-5">
    <%= show_errors(@user) %>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <h2 class="form-signin-heading">Reset Password</h2>
    <%= form_for @user, url: update_password_user_path(@user), html: {method: :put}, class: "form-signin" do |f| %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: "" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password" %>
      <%= hidden_field_tag :token, @token %>
      <%= f.submit "Change password", class: "btn btn-lg btn-dark btn-block", id: "submit_user" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% title "Register a User" %>

<div class="row">
  <div class="col-md-5">
    <%= show_errors(@user) %>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <h2 class="form-signin-heading">New user</h2>
    <%= render "form" %>
  </div>
</div>

app/views/users/new_act_email.html.erb
<% title "Resend your Activation Email" %>

<div class="row">
  <div class="col-md-4">
    <h2 class="form-signin-heading">Resend activation email</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= form_tag send_act_email_users_path, class: "form-signin" do %>
      <%= text_field_tag "email", nil, class: "form-control", placeholder: "Email", autofocus: "" %>
      <%= submit_tag "Resend activation email", class: "btn btn-lg btn-dark btn-block", id: "resend_activation" %>
    <% end %>
  </div>
</div>

app/views/users/new_reset_password.html.erb
<% title "Password Recovery" %>

<div class="row">
  <div class="col-md-3">
    <h2 class="form-signin-heading">Forgot Password?</h2>
    <%= form_tag create_reset_password_users_path, class: "form-signin" do %>
      <%= text_field_tag "email", nil, class: "form-control", placeholder: "Email", autofocus: "" %>
      <%= submit_tag "Reset my password", class: "btn btn-lg btn-dark btn-block", id: "reset_password" %>
    <% end %>
  </div>
</div>

app/views/users/new_session.html.erb
<% title "Login" %>

<div class="row">
  <div class="col-md-3">
    <h2 class="form-signin-heading"><%= yield(:title) %></h2>
      <%= form_tag create_session_users_path, class: "form-signin" do %>
        <%= text_field_tag "email", nil, class: "form-control", placeholder: "Email", autofocus: "" %>
	       <%= password_field_tag "password", nil, class: "form-control", placeholder: "Password" %>
	       <%= label_tag nil, class: "checkbox" do %>
	         <%= check_box_tag :remember %> keep me logged in
	       <% end %>
	       <%= submit_tag "Login", class: "btn btn-lg btn-dark btn-block", id: "login_user" %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <%= link_to "Forgot password?", new_reset_password_users_path, class: "badge badge-light" %> |
				<%= link_to "Resend activation email", new_act_email_users_path, class: "badge badge-light" %>
  </div>
</div>