config/routes.rb
Rails.application.routes.draw do
  root "rooms#index"

  resources :users, only: [:new, :create] do
    get :activate, on: :member
    get :edit_password, on: :member
    post :update_password, on: :member
    put :update_password, on: :member
  end

  resource :users, only: [] do
    get :new_session
    post :create_session
    get :destroy_session
    get :new_act_email
    post :send_act_email
    get :new_reset_password
    post :create_reset_password
  end

  get "register" => "users#new",             as: :register
  get "login"    => "users#new_session",     as: :login
  get "logout"   => "users#destroy_session", as: :logout

  resources :rooms, only: [:index, :show]
  resource :rooms, only: [] do
    post :publish
  end

  resources :bids, only: [:create] do
  end
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id                :integer          not null, primary key
#  name              :string           not null
#  expires_at        :datetime         not null
#  minimal_bid       :integer          not null
#  winner_bid        :integer          default(0)
#  winner_bid_id     :integer
#  winner_user_email :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  amount_of_bids    :integer          default(0)
#

class Room < ApplicationRecord

  # constants
  #--------------------------------------------------------------
  ROOM_TYPE = ["Penthouse", "Suite", "Deluxe Room"].freeze
  MINIMAL_INCREASE_BID = 1.05.freeze

  # associations
  #--------------------------------------------------------------
  has_many :bids, dependent: :destroy

  # validations
  #--------------------------------------------------------------
  validates_presence_of :name
  validates_presence_of :expires_at
  validates_presence_of :minimal_bid

  # scopes
  #--------------------------------------------------------------
  scope :active, -> { where("expires_at > ?", Time.now) }
  scope :by_remaining_time, -> { order(expires_at: :asc) }

  # instance methods
  #--------------------------------------------------------------

  # is room active to accept bids?
  def active?
    self.expires_at > Time.now
  end

  # has room any winner bid?
  def has_any_winner?
    self.winner_bid.positive?
  end

  # is bid amount a winner?
  def is_a_winner?(bid_amount)
    bid_amount >= self.minimal_allowed_bid
  end

  # return the minimal allowed bid
  def minimal_allowed_bid
    if self.winner_bid.positive?
      (self.winner_bid * MINIMAL_INCREASE_BID).to_i
    else
      self.minimal_bid
    end
  end

  # update room details for the new winner
  def set_new_winner!(bid, user)
    new_attributes = {
      winner_bid: bid.amount,
      winner_bid_id: bid.id,
      winner_user_email: user.email
    }
    if (self.expires_at - bid.created_at) < 1.minute
      new_attributes[:expires_at] = self.expires_at + 1.minute
    end
    self.update_attributes new_attributes
  end

  # class methods
  #--------------------------------------------------------------

  # publish some sample rooms for auctions
  def self.create_sample_rooms!
    return unless self.active.empty?
    require "faker"
    Room.destroy_all
    Faker::Number.between(10, 20).times do
      new_room = {
        name: "#{ROOM_TYPE.sample} in Hotel #{Faker::Company.name} (#{Faker::Address.city})",
        expires_at: rand(20.minutes.from_now..30.minutes.from_now),
        minimal_bid: Faker::Number.between(10, 50) * 100
      }
      room = self.create new_room
      Faker::Number.between(5, 10).times do
        amount = Faker::Number.between(10, 50) * 100
        new_bid = {
          amount: amount,
          accepted: room.is_a_winner?(amount) ? true : false,
          user_email: Faker::Internet.email,
          user_id: 1
        }
        new_bid[:rejection_cause] = "Bid is not >= #{room.minimal_allowed_bid}" unless new_bid[:accepted]
        bid = room.bids.create new_bid
        room.update_attributes winner_bid: amount, winner_bid_id: bid.id, winner_user_email: new_bid[:user_email] if new_bid[:accepted]
      end
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  skip_before_action :require_login, only: [:index, :show]

  def index
    @rooms = Room.active.by_remaining_time
  end

  def show
    @room = Room.includes(:bids).find(params[:id])
    @bids = Bid.where(room_id: @room.id).page(params[:page]).per_page(Bid::BIDS_PER_PAGE)
  end

  def publish
    Room.create_sample_rooms!
    redirect_to rooms_path
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper

  # show if the bid amount in the table if it'sis greater than zero
  def show_if_positive(winner_bid)
    winner_bid.positive? ? bath_currency_for(winner_bid) : ""
  end

  # render either the highest bid or the minimal bid
  def render_highest_bid_for(room)
    if room.has_any_winner?
      "<h4>The highest bid is <strong>#{bath_currency_for(room.winner_bid)}</strong></h4><h5> posted by <span class='text-blue'>#{room.winner_user_email}</span></h5>".html_safe
    else
      "<h4>The minimal bid is <strong>#{bath_currency_for(room.minimal_bid)}</strong></h4>".html_safe
    end
  end

  # render the remaining time or a message for expired auction
  def render_remaining_time(expiration_time)
    if expiration_time < Time.now
      "<h4></br><span id='expiration_status'>This Auction has </span><span class='text-blue'>FINISHED</span></h4>".html_safe
    else
      "<h4></br><span id='expiration_status'>Remaining Time: </span><span class='expiration-time-room text-green hidden'>#{time_in_milliseconds(expiration_time)}</span></h4>".html_safe
    end
  end

  # format bid.created_at timestamp
  def format_time(time)
    time.strftime("%d/%m/%Y %H:%M:%S")
  end

  # render the status of the bid (accepted/rejected)
  def render_bid_status(accepted)
    if accepted
      status = "ACCEPTED"
      color_class = "text-green"
    else
      status = "REJECTED"
      color_class = "text-red"
    end
    "<span class='#{color_class}'>#{status}</span>".html_safe
  end

  # show amount with Bath currency symbol
  def bath_currency_for(amount)
    "#{amount} &#3647".html_safe
  end

end

app/views/rooms/index.html.erb
<% title "Welcome to Hotels Rooms Auctions" %>

<h1 class="page-header"><%= yield :title %></h1>

<% if @rooms.empty? %>
  <%= link_to("Create Sample Data", publish_rooms_path, method: :post, class: "btn btn-dark", id: "publish_rooms") %>
<% else %>
  <table class="table table-sm table-striped" id="rooms_table">
    <thead>
      <tr>
  						<th scope="col">Hotel Room</th>
  						<th scope="col">Minimal Bid</th>
  						<th scope="col">Winner Bid</th>
  						<th scope="col">Winner User</th>
  						<th scope="col">Remaining Time</th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr scope="row" id="<%= dom_id(room) %>">
          <td><%= link_to room.name, room_path(room), id: "link_to_#{dom_id(room)}" %></td>
  						  <td><%= bath_currency_for(room.minimal_bid) %></td>
  						  <td><strong><%= show_if_positive(room.winner_bid) %></strong></td>
  						  <td><%= room.winner_user_email %></td>
  						  <td><span class="expiration-time-table text-green hidden"><%= time_in_milliseconds(room.expires_at) %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/rooms/show.html.erb
<% title @room.name %>

<h1 class="page-header text-gray"><%= yield :title %></h1>

<div class="row">
  <div class="col-md-8">
				<%= render_highest_bid_for(@room) %>
		</div>
  <div class="col-md-4 text-right">
				<%= render_remaining_time(@room.expires_at) %>
		</div>
</div>
</br>

<% if @room.active? %>
  <%= form_for Bid.new, html: {class: "form-inline"} do |f| %>
    <%= f.hidden_field :room_id, value: @room.id, id: "bid_room_id" %>
				<div class="form-group mb-2">
				  <%= f.label :amount, "<strong>Place a Bid</strong>".html_safe %>
				</div>
				<div class="form-group mx-sm-3 mb-2">
				  <%= f.text_field :amount, class: "form-control", placeholder: "must be >= #{bath_currency_for(@room.minimal_allowed_bid)}".html_safe, autofocus: "", id: "bid_amount" %>
				</div>
				<%= f.submit "Post Bid!", class: "btn btn-dark mb-2", id: "submit_bid" %>
		<% end %>
<% end %>

<% if @room.bids.empty? %>
  <div><h5 class="text-red">Nobody posted bids for this Room</h5></div>
		<% else %>
		<div>
  <table class="table table-sm" id="bids_table">
    <thead>
      <tr>
  						<th scope="col">#</th>
  						<th scope="col">User</th>
								<th scope="col">Posted At</th>
								<th scope="col">Rejection Cause</th>
  						<th scope="col">Status</th>
								<th scope="col">Bid</th>
      </tr>
    </thead>

    <tbody>
      <% @bids.each do |bid| %>
        <tr scope="row" id="<%= dom_id(bid) %>">
								  <td><%= bid.id %></td>
								  <td><%= bid.user_email %></td>
          <td><%= format_time(bid.created_at) %></td>
										<td><%= bid.rejection_cause.html_safe unless bid.rejection_cause.nil? %></td>
										<td><%= render_bid_status(bid.accepted) %></td>
										<td><strong><%= bath_currency_for(bid.amount) %></strong></td>
        </tr>
      <% end %>
    </tbody>
  </table>
		<%= will_paginate @bids %>
		</div>
<% end %>

<script>
  <% if defined?(PusherFake) %>
  var pusherInstance = <%== PusherFake.javascript %>
		<% else %>
  var pusherInstance = new Pusher("<%= ENV['PUSHER_KEY'] %>", {
    wsHost: "ws.pusherapp.com",
    httpHost: "sockjs.pusher.com",
    encrypted: true
  });
  <% end %>

  var roomId = <%= @room.id %>

  if (pusherInstance.connection.state === "connected") {
    console.log("new connection to Pusher created!");
  }

  var channel = pusherInstance.subscribe("auctions");

  if (channel.name === "auctions" && channel.subscribed === true) {
    console.log("Pusher subscribed to channel 'auctions'");
  }

  var event = "new_bid_in_room_" + roomId;

  channel.bind(event, function(data) {
    console.log("received event for channel 'update_url_latest' with data", data);
    window.location.reload(true);
  });

  if (channel.callbacks._callbacks["_" + event] !== void 0) {
    console.log("Pusher channel 'auctions' binded to events '" + event + "'");
  }
</script>